package main

func main() {
	// fmt.Println("Hello World")
	// c := add(5, 6)
	// println(c)
	// z := Boolean()
	// println(z)
	// showvar()
	// loop1()
	// loop2()
	// loop3()
	// loop4()
	// loop5()
	// oddeven()
	// days()
	// whatday(4)
	// arr1()
	// arr2()
	// matrix()
	// imatrix(3)
	// slice1()
	// slice2()
	// slice3()
	// pointer1()
	pointer2()
	// variadic()
	// recursion()
	// recursionPattern(5)
	// sortdemo()
	// structDemo()
	// advancedSlice()
	// readFileDemo()
	// writeFileDemo()
	// mapDemo()
	// methodDemo()
	// interfaceDemo()
	// goRoutine()
	// channelDemo()
	// executeCountWaitGroup()
	// executeCountChannel()
}
